---
  - name: Add key 
    apt_key:
      keyserver=hkp://keys.gnupg.net
      id={{ item }}
    with_items:
    - 409B6B1796C275462A1703113804BB82D39DC0E3 
    - 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

  - name: install packages
    apt:
      name={{ item }}
    with_items:
      - software-properties-common

  - name: add APT repo
    apt_repository:
      repo: 'ppa:rael-gc/rvm'
      state: present
  
  - name: install rvm
    apt:
      update_cache=yes    
      name={{ item }}
    with_items:
      - rvm

  - name: rvm install ruby 2.2.4 - this could take some time
    shell:  'bash -lc "/usr/share/rvm/bin/rvm install 2.2.4"'

  - name: --default 2.2.4
    shell: 'bash -lc "rvm use --default 2.2.4"'

  - name: gem install rails  - this could also take some time
    shell: 'bash -lc "gem install rails --no-ri --no-rdoc"'
  
  - name: initialize ror application
    shell: 'bash -lc "Y | rails new test_app -d postgresql"'
    args:
      chdir: /var/www/
 
  - name: install depedencies
    shell: 'bash -lc "bundle install"'
    args:
      chdir: /var/www/test_app

  - name: prepare database.yml
    template:
      src: database.yml.j2
      dest: /var/www/test_app/config/database.yml

  - name: chown www-data of app
    command: chown -R www-data:www-data /var/www

  - name: create log file
    command: touch log/development.log && chmod 0666 log/development.log
    args:
      chdir: /var/www/test_app

  - name: install node 
    shell: 'bash -lc "cd /tmp && \curl -sSL https://deb.nodesource.com/setup_6.x -o nodejs.sh && cat /tmp/nodejs.sh | sudo -E bash - && sudo apt-get install -y nodejs"'

  - name: create DBs
    command: su - postgres -c "cd /var/www/test_app && rake db:create"
    
  - name: setup nginx to use rails test app
    template:
      src: default.j2
      dest: /etc/nginx/sites-available/default	

  - name: restart nginx
    service:
       name=nginx
       state=restarted
       enabled=yes

