---

  - name: install packages
    apt:
      name={{ item }}
      update_cache=yes
    with_items:
      - postgresql 
      - postgresql-contrib 
      - pgadmin3
      - libpq-dev

  - name: restart postgreSQL
    service:
      name=postgresql
      state=restarted
      enabled=yes

  - name: check if user exists
    shell: psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='ror_app'"
    register: user_exists
    become: true
    become_user: postgres

  - name: create user for DB
    shell: psql -c "CREATE ROLE ror_app WITH CREATEDB LOGIN PASSWORD 'testpass';"
    when: user_exists.stdout != '1'
    become: true
    become_user: postgres